### ISSUE TITLE
Deselect All takes forever in TailoringWindow

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/scap-workbench#1]
It does finish successfully but it takes roughly 5 seconds on my PC.

Undoing Deselect All or redoing it also takes forever.

This issue manifests itself on both 1.0.x and the new 1.1.x branches.

Original trac ticket: https://fedorahosted.org/scap-workbench/ticket/284

**Comment by mpreisler** [comment]
5536c962b134a938bd7c4c9d64c7ed6a1e044603 adds code that switches to the wait cursor while macros are undone / redone. At least user knows the application hasn't frozen.

In a way it's just putting lipstick on a pig and this will have to be fixed for real in the future.

**Comment by mpreisler** [comment]
One more note, the figures are for RHEL6 SSG. In general it applies to very large XCCDF files, with hundreds of rules.

With smaller content files this is not an issue it all.

**Comment by WesleyCeraso** [comment]
Fixed by #113

**Comment by WesleyCeraso** [comment]
Reopening this issue so that I can use it for a refactoring that improved the performance of "Deselect All".

**Comment by mpreisler** [comment]
@WesleyCeraso you don't need issues to make pull requests btw, there is no such requirement in github upstream development.
