### ISSUE TITLE
Scan using Normal User, User w NOPASSWD, Root

### ISSUE THREAD

**Issue by jgalleri** [OpenSCAP/scap-workbench#108]
Hello,

I came across multiple error running just a custom command (uninstall tftp-server) using normal account. I added NOPASSWD since I thought its interactive password issue, still error. Finally, I enabled root login and used workbench to connect to destination server as root, and tftp-server was uninstalled successfully. I am sure workbench doesn't need root. Any recommendations?

Error (Normal Account w Sudo Access)

Fix execution completed and returned: 0
infoÂ  Failed to stop snmpd.service: Interactive authentication required.
Failed to execute operation: Interactive authentication required.
infoÂ  Failed to verify applied fix: Checking engine returns: fail

Error (with NOPASSWD)
Fix execution completed and returned: 1
infoÂ  Loaded plugins: rhnplugin
*Note* Spacewalk repositories are not listed below. You must run this command as root to access Spacewalk repositories.
Repository rs-epel is listed more than once in the configuration
You need to be root to perform this command.
infoÂ  Failed to verify applied fix: Checking engine returns: fail

Issue Fixed after using "root" account.

Thank you,

John

**Comment by jgalleri** [comment]
Anyone?

**Comment by mpreisler** [comment]
SCAP Workbench itself doesn't care what the user is. However for remediations to work, that user has to have privileges to perform the remediations.

Check out #46

**Comment by WesleyCeraso** [comment]
Support provided. Improvement will be tracked by #46
