### ISSUE TITLE
User and host field is wiped after ssh scan

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/scap-workbench#109]
```
$ scap-workbench --version
13:44:55 | info     | SCAP Workbench 1.1.4, compiled with Qt 4.8.7, using OpenSCAP 1.2.13
```
When I start remote scan, text in field "User and host" is reset to `username@hostname` so I cannot see what I am scanning - and I cannot repeat scan quickly.

**Comment by yuumasato** [comment]
Fixed by #111
