### ISSUE TITLE
Remote scan related GUI looks disable even though it isn't

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/scap-workbench#11]
From Matt Reid:

> Switching over to remove machine (over ssh) reveals a field, spinner, and dropdown that all look 
> disabled, because they match the gray of the dialog itself. Because they're active and can be 
> interacted with, they shouldn't use a gray background.

Original trac ticket: https://fedorahosted.org/scap-workbench/ticket/265

**Comment by mpreisler** [comment]
This is desktop theme related. On my system I have white widgets.

**Comment by mpreisler** [comment]
No idea how to fix this without hardcoding colors. I want to avoid that because people may have dark desktops or some other strange setups and they might not even see the text then.

Postponing until I can figure out what's wrong.

**Comment by WesleyCeraso** [comment]
We could not reproduce this issue. It seems to be a local problem or already fixed.
