### ISSUE TITLE
Not able to remove locally installed version with ```make uninstall``` 

### ISSUE THREAD

**Issue by dahaic** [OpenSCAP/scap-workbench#115]
As the uninstall target is not provided in the Makefile, it is not possible to remove locally installed version without manual cleanup, which is tedious and error-prone.

As I consider this basic functionality, I mark this ticket as a bug.

**Comment by mpreisler** [comment]
https://cmake.org/Wiki/CMake_FAQ#Can_I_do_.22make_uninstall.22_with_CMake.3F

**Comment by yuumasato** [comment]
What would be the bumblebee situation? Could not find any reference.

**Comment by mpreisler** [comment]
Check out https://github.com/MrMEEE/bumblebee-Old-and-abbandoned/issues/123

It used to be the most commented commit ever on GitHub but I can't find it
anymore.
