### ISSUE TITLE
Improve UX of RemoteMachineCombobox

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/scap-workbench#12]
From Matt Reid:

> Could we remove the empty looking dropdown to the right of the port for SSH and build that into the 
> field they enter their user and hostname? It would make more sense if that was the dropdown you 
> could select from for your history, and change the field to what you selected, rather than how it 
> works now with the dropdown that always stays empty, but can be used to modify the host field to a 
> previous value. Similar to the Remote Desktop Viewer Host field when entering a host to connect to.

Original trac ticket: https://fedorahosted.org/scap-workbench/ticket/294

**Comment by ybznek** [comment]
+1
it is very "WTF" for me, when the menu is empty and not enabled and without title.

**Comment by yuumasato** [comment]
The list of recent remote machines scanned had its UI improved, see https://github.com/OpenSCAP/scap-workbench/pull/86/.

The improvement made is not as suggested by reporter but I think it is enough to avoid confusion and "WTF" feelings.

Any other comments or improvements before closing this?

**Comment by mpreisler** [comment]
Agreed.
