### ISSUE TITLE
Add way to reload datastream

### ISSUE THREAD

**Issue by dahaic** [OpenSCAP/scap-workbench#134]
When developing something, I often rebuild datastream and then want to reload it in SCAP Workbench. Currently, there is no option to just reload, so I need to click through directory tree every time this happens.

It would be useful to have such option (for example in ```File/Reload Content```)

It would be great to have also customization preserved.

**Comment by WesleyCeraso** [comment]
I think it should check for changes in the file each X seconds plus when the mainwindow gets focus and just before the scanning. If the file changed it opens a message box asking if the user wants to reload the file or use the old version (it would need some work).

I'm not sure about the customization, I don't know if the scap lib can handle the situation where a customized rule no longer exists in the new version of the file.

**Comment by dahaic** [comment]
I would prefer to have an option there, not the automatic reload, as that would create too much complexity for little benefit.

For the customization - let's use default behavior of SCAP Workbench (whatever it is). I just wanted to avoid situation that it drops customization and I have to create it again, which is painful.

**Comment by mpreisler** [comment]
@WesleyCeraso We can use https://doc.qt.io/qt-4.8/qfilesystemwatcher.html which is much better than any polling solution.

**Comment by mpreisler** [comment]
IMO it should always ask whether you want to reload because it may be dangerous. But we can automatically figure out that the file changed and offer a choice to the user.

**Comment by cipherboy** [comment]
Fixed by #177.
