### ISSUE TITLE
Symantec Endpoint Protection quarantines SCAP Workbench MSI as a Virus

### ISSUE THREAD

**Issue by groovycoop** [OpenSCAP/scap-workbench#135]
Employer requires Symantec to scan files and will not allow me to download/install due to virus detection.
Could you verify the installer is clean.  Also any help, suggestions, greatly appreciated.

Scan type: Auto-Protect Scan
Event: Security Risk Found!
Security risk detected: WS.Reputation.1
File: c:\users\USER\downloads\scap-workbench-1.1.5-1.msi
Location: Quarantine
Computer: COMPUTER NAME
User: USER
Action taken: Quarantine succeeded
Date found: Monday, July 17, 2017  5:57:01 PM

**Comment by redhatrises** [comment]
Syamtec A/V is quarantining this because the application is not in the Symantec whitelist. `scap-workbench` could be submitted to Symantec for whitelist approval at https://submit.symantec.com/whitelist/isv/. It would just have to be done for every release version.

**Comment by WesleyCeraso** [comment]
@redhatrises Thanks for the information. I already added it to the release guide.

**Comment by WesleyCeraso** [comment]
I have submitted the current msi to the whitelist, it should be ok in a matter of days I suppose. Thanks for the report.
