### ISSUE TITLE
SCAP Workbench compiled without remote scanning support

### ISSUE THREAD

**Issue by jeffstoner** [OpenSCAP/scap-workbench#14]
Just downloaded SCAP Workbench 1.1.0 for Windows (msi installer from http://martin.preisler.me/2015/03/scap-workbench-1-1-0/). The options for Target and the Scan button are greyed-out. When I mouse-over the Target options, the tool tip says it was not compiled with remote scanning support.
![scap_workbench_win_110](https://cloud.githubusercontent.com/assets/1587365/6952829/3886e248-d893-11e4-94fb-4bbf03a92ab1.png)

I'm running Win 7 Pro, SP1, 64-bit.

**Comment by jeffstoner** [comment]
Does this hold any possibility of working?
http://www.dereckson.be/blog/2013/08/31/use-ssh-agent-on-windows/

**Comment by mpreisler** [comment]
That might work for keys.

However, I think users will overwhelmingly want to use password auth. Especially on Windows where SSH keys are very rare. As the first step I want to get password auth working, then I will worry about ssh key auth.

We could really use somebody from openssh or cygwin or both here.

**Comment by jeffstoner** [comment]
For what it's worth, I'm willing to help test/document this aspect of the tool (that is, using Workbench from Windows to remote scan Linux servers.) If I can assist, point me in a direction.

**Comment by mpreisler** [comment]
Unfortunately we can't move forward with this ticket without patching either OpenSSH or Cygwin. Emailed Corinna Vinschen from the Cygwin project and it seems patching OpenSSH is the easier route. The Cygwin issue regarding passing descriptors via AF_LOCAL/AF_UNIX sockets is fairly old and hard to solve.

As I don't know the OpenSSH codebase, any help is appreciated.

**Comment by jeffstoner** [comment]
While this is only an announcement of an intent, if they hold to their word, it may provide another avenue to explore:  http://blogs.msdn.com/b/looking_forward_microsoft__support_for_secure_shell_ssh1/archive/2015/06/02/managing-looking-forward-microsoft-support-for-secure-shell-ssh.aspx

**Comment by mpreisler** [comment]
@Jakuje patched ssh to work on Windows.

See https://github.com/Jakuje/stuff/commit/1a1546a0d0eb2f855c02f16ef0dfbb96da5ccb0f

 I am looking into the patch, so far it looks very promising.

**Comment by mpreisler** [comment]
@jeffstoner I have good news :-) Check out http://martin.preisler.me/2015/03/scap-workbench-1-1-0/ and http://martin.preisler.me/wp-content/uploads/2015/03/scap-workbench-1.1.0-win32-remote-scan-testing.zip

From my testing I can scan `Fedora` and `RHEL6` remotely from a `Windows7` box. Can you confirm that it works for you? Keep in mind that the `askpass` dialog is not polished and kind of strange,  when it asks about host confirmation you have to type `yes` into the askpass dialog. This will be improved for the final release.

![sw_win_remote_scan](https://cloud.githubusercontent.com/assets/753153/8452929/9a96b334-1fef-11e5-8bc5-d2136839ec79.png)

**Comment by jeffstoner** [comment]
Sweeeeeeeeeeeeeeeet!
Downloaded, installed and executed on Win7Pro (against a server that didn't have openscap installed but it did connect.)

I'll start running some tests and update this ticket with results.

Thanks again!

**Comment by mpreisler** [comment]
Hi @jeffstoner 

Any news?

**Comment by mpreisler** [comment]
Hi @jeffstoner 
I have heard about some minor issues but it looks like this is worthy of inclusion in the end. Do you have any feedback?

I want to solve a few remaining issues and then release 1.1.1 with the remote scan support on Windows.

**Comment by jeffstoner** [comment]
Sorry. I was under the gun to meet a deadline for my project. I was anticipating using this when I build the servers but that's waiting on an executive decision (go figure.) Let me dig up some older (non-production) servers that I can munge.

**Comment by mpreisler** [comment]
This has been fixed.
