### ISSUE TITLE
scap-workbench remote machine with (example port) 50.000 or 60.000, result port 22 in dry run.

### ISSUE THREAD

**Issue by donixa** [OpenSCAP/scap-workbench#140]
scap-workbench remote machine with port 50.000 or 60.000, result port 22 in dry run.

Produced in:
CentOS 7 x64 or RHEL 7 x64
SCAP Workbench 1.1.4, compiled with Qt 4.8.5, using OpenSCAP 1.2.14

Open it, click remote machine, change port to 50000 or 60215 or 60000
dry run
click scan
result: oscap-ssh root@target-ip 22 ...............................................................

I see at maximum it correctly display until 32767.

**Comment by donixa** [comment]
**remote scan via LAN SSH port 22:**

from RHEL 7 to CentOS 7, result **not applicable**,
which I guess this is expected behavior

from CentOS 7 to CentOS 7, result is expected,
**its working,**

**Remote scan via INTERNET, Using port forwarding for example SSH:60215 into SSH:22**
"Checking if oscap is available on target machine....."
and then:
**error    
Failed to locate oscap on remote machine. Please, check that openscap-scanner is installed on the remote machine.**

Please fix this, I believe it has something todo with the port,

**Comment by WesleyCeraso** [comment]
@donixa thanks for reporting it, it's fixed now and will be in the next release.
