### ISSUE TITLE
Scan failed on Windows 10 with 1.1.5

### ISSUE THREAD

**Issue by colinli** [OpenSCAP/scap-workbench#145]
Error msg:
```
17:28:48 
info     
SCAP Workbench 1.1.5, compiled with Qt 4.8.7, using OpenSCAP 1.3.0

17:28:57 
info     
Opened file 'C:/Program Files (x86)/scap-workbench/ssg/ssg-centos6-ds.xml'.

17:29:16 
info     
Establishing connecting to remote target...

17:29:17 
error    
Can't connect to remote machine! Exception was: There was a problem with SshConnection!
Failed to create SSH master socket!
Diagnostic info: Starting process 'ssh.exe -M -f -N -o ServerAliveInterval=60 -o ControlPath=D:/Temp/SSn9G2/ssh_socket -p 22 cli@xxx.xxx.xxx.xxx'
Starting process 'ssh.exe -M -f -N -o ServerAliveInterval=60 -o ControlPath=D:/Temp/SSn9G2/ssh_socket -p 22 cli@xxx.xxx.xxx.xxx' 
stdout: 
=============================== 
stderr: 
=============================== 
Could not create directory '/home/cli2/.ssh'.
1 [main] ssh 18080 child_info_fork::abort: C:\Program Files (x86)\scap-workbench\cygcrypto-1.0.0.dll: Loaded to different address: parent(0xFA0000) != child(0x1010000)
ssh_askpass: fork: Resource temporarily unavailable
Host key verification failed. 
```

**Comment by matejak** [comment]
Hello, thank you for using `oscap-workbench`! We will look into your issue as soon as time constraints permit.

**Comment by colinli** [comment]
I tried to create home/cli2 in the root directory in scap-workbench but no lucky.

**Comment by matejak** [comment]
We are investigating your issue, and so far it seems to be a problem with the bundled ssh. We cross-compile `scap-workbench` to distribute it on Windows, and we bundle some SSH executables and libraries from third parties. It is quite likely that the SSH library doesn't work on your system. We will discuss this - as things have changed recently and it is possible to install a native SSH client quite easily, the best solution could be to use the native SSH.

**Comment by matejak** [comment]
This seems to be the same problem:
https://unix.stackexchange.com/questions/55909/cygwin-readline-lib-loaded-in-different-locations

- The issue may be caused by updating some of the DLLs that are involved in the SSH process.
- Have you installed any of the [blacklisted apps](https://cygwin.com/faq/faq.html#faq.using.bloda)? If so, if you can, try to uninstall them.
- Finally, have you tried to restart the system and trying again? It may actually help.

**Comment by mpreisler** [comment]
> we bundle some SSH executables and libraries from third parties.

For what it's worth it's @Jakuje 's ssh build, not really a third party. Maybe he is able to shed some light into this.

**Comment by colinli** [comment]
Restart the machine works like a charm! Thanks!

**Comment by Jakuje** [comment]
Good to hear it got resolved by reboot. As already mentioned in the link, there might be issues with `fork()` in Windows. The solution is not ideal and using the way upstream is trying to do now (#96) would be preferred (though it would probably not resolve these rare problems).

From the upstream bug, I am not sure about the state of the change (something is committed, not tested, but bug still open) so at least it would be worth giving it a shot and test it. If it will not do what it is supposed to do, I might find some time to have a look into that, but I don't have any Windows system at hand to test.
