### ISSUE TITLE
The 'oscap' process has written the following content to stderr: ERROR:pkexec.c:142:pam_conversation_function: code should not be reached

### ISSUE THREAD

**Issue by servebeer** [OpenSCAP/scap-workbench#146]
Every time I try to start a scan via SCAP Workbench, it errors out the following two errors:

```
The 'oscap' process has written the following content to stderr:
ERROR:pkexec.c:142:pam_conversation_function: code should not be reached

The 'oscap' process has written the following content to stderr:
/usr/libexec/scap-workbench-pkexec-oscap.sh: line 32: 6474 Aborted $PKEXEC_PATH --disable-internal-agent "$SCAP_WORKBENCH_OSCAP" $uid $gid "$@" 2> >(tail -n +2 1>&2) 
```

SCAP Workbench is running on RHEL 7.4.

**Comment by matejak** [comment]
Hello, thank you for using openscap!
The issue you have seems not to be directly related to `openscap`. The `/usr/libexec/scap-workbench-pkexec-oscap.sh` script uses `pkexec` to obtain sudo-like functionality and it seems that your `pkexec` (or its configuration) has an issue, the `code should not be reached` looks like a bug.
What does `pkexec --disable-internal-agent ls` do in your system? It should ask you for password and then it should execute `ls` as root without any ado.

**Comment by servebeer** [comment]
Hello,

When I execute the command, I am prompted for my password and then I get this error:



$ pkexec --disable-internal-agent ls

**

ERROR:pkexec.c:142:pam_conversation_function: code should not be reached

Aborted



This is probably due to some "hardening" scripts that I had to run on the system before I was allowed to join it to the network.



Jon





---- On Wed, 01 Nov 2017 11:43:30 -0500 Matěj Týč &lt;notifications@github.com&gt; wrote ----




Hello, thank you for using openscap!

 The issue you have seems not to be directly related to openscap. The /usr/libexec/scap-workbench-pkexec-oscap.sh script uses pkexec to obtain sudo-like functionality and it seems that your pkexec (or its configuration) has an issue, the code should not be reached looks like a bug.

 What does pkexec --disable-internal-agent ls do in your system? It should ask you for password and then it should execute ls as root without any ado.


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.









WARNING: Computer viruses can be transmitted via email. The recipient should check this email and any attachments for the presence of viruses. IrishTech accepts no liability for any damage caused by any virus transmitted by this email. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission.

**Comment by matejak** [comment]
OK, so this confirms that it is not an `openscap` bug, but something went wrong with your `pkexec` due to the hardening that you have mentioned. Therefore, you should reach out for help to the IT support in your institution.
However, as you mention that you use RHEL, they should be able to sort it out with the RedHat support quite easily.
