### ISSUE TITLE
Custom SSH ports do not connect

### ISSUE THREAD

**Issue by Hyper200** [OpenSCAP/scap-workbench#159]
Hi There,

I think i have found a bug in scap-workbench.

When attempting to connect to a system with an ssh port other than port 22 the connection times out. The dryrun command shows the following:

oscap-ssh user@51.140.70.112 22 xccdf eval --datastream-id scap_org.open-scap_datastream_from_xccdf_ssg-rhel7-xccdf-1.2.xml --xccdf-id scap_org.open-scap_cref_ssg-rhel7-xccdf-1.2.xml --profile xccdf_org.ssgproject.content_profile_C2S --oval-results --results /tmp/xccdf-results.xml --results-arf /tmp/arf.xml --report /tmp/report.html "C:/Program Files (x86)/scap-workbench/ssg/ssg-rhel7-ds.xml"

Even though the port 55448 was picked.

The actual connection with dry run is not picked also fails due to to incorrect port use.

Thanks

Joe.

**Comment by yuumasato** [comment]
Hello, which version are you using?
It looks like issue #140 fixed v1.1.6

**Comment by Hyper200** [comment]
Ah downloaded the latest version from the website which is 1.1.5 - I guess this is a duplicate and can be closed!

**Comment by mpreisler** [comment]
Thx for confirming, @Hyper200 !
