### ISSUE TITLE
Button events need to be triggered on button release

### ISSUE THREAD

**Issue by zemb** [OpenSCAP/scap-workbench#18]
The actions on buttons (except in standard dialogs with Ok/Cancel, Yes/No) are triggered when the pointer is leaving a depressed button. This usually means that the user changed his mind and does not want to trigger it, I think.

This manifests in current RHEL-6 scap-workbench-1.0.3-2.el6 and RHEL-7 version.

**Comment by mpreisler** [comment]
Thanks for the report. It turns out SCAP Workbench is using the `released` signal and it should be using `clicked` signal.

I will change this in all maintenance branches because I consider it a bug.

**Comment by mpreisler** [comment]
Fixed with 3e48823bd4fa05855d47a7726b73066608cb11de
