### ISSUE TITLE
macOS release/binary for 1.2.0?

### ISSUE THREAD

**Issue by brianmorton** [OpenSCAP/scap-workbench#192]
Will there be one? asking as a homebrew maintainer.

**Comment by redhatrises** [comment]
@brianmorton yes. There should have been a dmg automatically built, but some issues came up with Travis and upstream OpenSCAP.

**Comment by brianmorton** [comment]
Awesome, just update the releases page (or ping here / close this issue) when its resolved!

Thanks.

**Comment by matejak** [comment]
FYI, there is also the #163 issue.

**Comment by brianmorton** [comment]
OK thanks @matejak - is there a timeline for this stuff? We don't generally like to host outdated binaries at homebrew, so if there is no known solution to this we may just remove this app and it can be re-added later if/when you fix it.

**Comment by redhatrises** [comment]
@brianmorton it should be fixed in a few days once the issues in PR #191 have been addressed and the PR itself merged.

**Comment by brianmorton** [comment]
OK I'll sit tight!

**Comment by redhatrises** [comment]
@brianmorton updated the release to contain the 1.2.0 DMG.

**Comment by brianmorton** [comment]
https://github.com/Homebrew/homebrew-cask/pull/50019
