### ISSUE TITLE
Problems with temporary directories

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/scap-workbench#196]
Version: scap-workbench-1.2.0-1.fc27.x86_64

See the Window that appeared after finished scanning Standard Fedora profile.
![screenshot from 2018-07-23 09-13-29](https://user-images.githubusercontent.com/9050916/43062350-ceac15f8-8e58-11e8-8dc6-2aa54ec939e8.png)

**Comment by mpreisler** [comment]
looks like a word splitting fail

**Comment by jan-cerny** [comment]
I have verified that this particular error has already been fixed in upstream by https://github.com/OpenSCAP/scap-workbench/pull/213.

However, there are different warning messages that pop up in this window. They haven't been fixed yet, but they have already been reported in https://github.com/OpenSCAP/scap-workbench/issues/187 and https://bugzilla.redhat.com/show_bug.cgi?id=1781074
