### ISSUE TITLE
"/usr/bin/setsid: invalid option -- 'w'" error message trying to remotely scan RHEL-6 system from RHEL-7 system using SCAP Workbench 1.1.0

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-workbench#20]
Description of problem:

Attempting to run a remote scan of RHEL-6 system (using ```ssg-rhel6-ds.xml```) from RHEL-7 system using SCAP Workbench 1.1.1 leads to the following error message:

```
# scap-workbench 
10:59:05 | info     | SCAP Workbench 1.1.1, compiled with Qt 4.8.5, using OpenSCAP 1.2.3
10:59:19 | info     | Opened file '/usr/share/xml/scap/ssg/content/ssg-rhel6-ds.xml'.
10:59:30 | info     | Establishing connecting to remote target...
10:59:30 | error    | Can't connect to remote machine! Exception was: There was a problem with SshConnection!
Failed to create SSH master socket! Diagnostic info: Starting process '/usr/bin/setsid -w /usr/bin/ssh -M -f -N -o ServerAliveInterval=60 -o ControlPath=/tmp/fCnqVu/ssh_socket -p 22 root@host'
Starting process '/usr/bin/setsid -w /usr/bin/ssh -M -f -N -o ServerAliveInterval=60 -o ControlPath=/tmp/fCnqVu/ssh_socket -p 22 root@host'
stdout:
===============================

stderr:
===============================
/usr/bin/setsid: invalid option -- 'w'

Usage:
 setsid [options] <program> [arguments ...]

Options:
 -c, --ctty     set the controlling terminal to the current one
 -h, --help     display this help and exit
 -V, --version  output version information and exit

For more details see setsid(1).
```

Note: True IP of the host above has been replaced with ```host```

How reproducible:
Always

Steps to reproduce:
```
1) Install openscap-1.2.3 from isimluk's COPR repository
2) git clone the most recent scap-workbench &&
    build it (according to Readme.md) &&
    make install it on the local system
3) git clone most recent scap-security-guide,
    build and install produced scap-security-guide RPM
4) run scap-workbench, select "ssg-rhel6-ds.xml" datastream file,
    try to perform remote scan from RHEL-7 system.
```
Current result:
After specifying the ```username@IP``` information in SCAP Workbench, and clicking 'Scan' button the aforementioned error message is displayed, and scan is terminated

Expected result:
Remote scan is performed properly.

Additional information:
```
[root@localhost ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.1 (Maipo)
[root@localhost ~]# rpm -qa | grep openscap
openscap-utils-1.2.3-0.1.el7.centos.x86_64
openscap-1.2.3-0.1.el7.centos.x86_64
openscap-scanner-1.2.3-0.1.el7.centos.x86_64
openscap-devel-1.2.3-0.1.el7.centos.x86_64
[root@localhost ~]# rpm -qa | grep scap-security-guide
scap-security-guide-0.1.22-1.el7.noarch
```

**Comment by mpreisler** [comment]
This is a pretty serious regression in all the maintenance branches. The issue was introduced in 40da1b6d9979f7b62a8738ef475e33be956d888f

As far as I can see, reverting this commit will fix the issue. It all stems from me misunderstanding what `setsid --wait` does

**Comment by mpreisler** [comment]
I decided to use `--wait` if available and ignore the exit code if `--wait` is not available.

If SSH fails the user will get notified of it from `stderr` and `stdout` of the ssh process. The UX won't be perfect but it will be decent enough.

I will patch the code to check whether `--wait` is supported at configure time.

**Comment by mpreisler** [comment]
fc6dd83acf5fbaadf2be2d18ff223dc603a6403b fixes the issue for v0-8 and v1-0. In those branches there is no configure-time check for setsid so we assume `--wait` is not supported.

**Comment by mpreisler** [comment]
49977564e4a4e67cf2985cab72574f7667e55927 fixes the issue for v1-1. We check at configure time, use `--wait` if supported.
