### ISSUE TITLE
lib change - test?

### ISSUE THREAD

**Issue by cipherboy** [OpenSCAP/scap-workbench#202]
Due to OpenSCAP/openscap#1158, the library so number will be changing. At minimum, we should update the OSX build:

https://github.com/OpenSCAP/scap-workbench/blob/v1-2/build-for-osx.sh#L7

(v1-2, which will get merged into master).

But we should also test that it builds with a new version of `scap-workbench`.

**Comment by cipherboy** [comment]
Never mind, #191 fixes this.

**Comment by cipherboy** [comment]
Except it needs to be backported for `v1-1`: https://github.com/OpenSCAP/scap-workbench/blob/v1-1/build-for-osx.sh#L7

**Comment by redhatrises** [comment]
This should be fixed now. Closing.
