### ISSUE TITLE
Using Pem keys 

### ISSUE THREAD

**Issue by dshiver** [OpenSCAP/scap-workbench#214]
I am setting this up using aws.  With workbench how do I add my key?

**Comment by cipherboy** [comment]
Workbench will use the ssh as you would from your terminal. So if you want
to add it to ~/.ssh/config with an IdentityFile under a Host entry,
workbench will pick that up for you. Same with id_rsa{,.pub} if you want to
add that to the EC2 instance.

(There might be other ways, I'm most familiar with this one).

**Comment by dshiver** [comment]
Ah, yeah didn't want to add my key directly to the EC2 instance.  Was wondering if anyone has had success getting in another way.

**Comment by cipherboy** [comment]
@dshiver Yeah, I'd try the `~/.ssh/config` option then. :)

**Comment by dshiver** [comment]
@cipherboy thanks.  looks like Im almost there.  I'm able to connect but it looks like I'm drawing errors and seeing a blank screen when I click show reports.
