### ISSUE TITLE
Can connect to remote machine but am getting errors for scan result

### ISSUE THREAD

**Issue by dshiver** [OpenSCAP/scap-workbench#215]
![image](https://user-images.githubusercontent.com/25825726/47464940-bdddc600-d79f-11e8-91e0-81cb146310cb.png)

**Comment by jan-cerny** [comment]
Hi @dshiver ,
This error message suggests that "oscap" command on the remote machine doesn't understand the SCAP file that contains rules. But I can't figure out the exact reason from this error message.
Could you please share with us what is the Profile you selected in SCAP Workbench? What is the operating system  on the remote machine?
Can you also run  `oscap -V` or `oscap --version` on the **remote** machine and paste the output here?
Thanks.

**Comment by dshiver** [comment]
I am selecting the "common profile for general purpose ubuntu systems"  Operating system is ubuntu 14.04.  I have also pasted the output below for oscap -V

OpenSCAP command line tool (oscap) 1.0.2
Copyright 2009--2014 Red Hat Inc., Durham, North Carolina.

==== Supported specifications ====
XCCDF Version: 1.2
OVAL Version: 5.10.1
CPE Version: 2.3
CVSS Version: 2.0
CVE Version: 2.0
Asset Identification Version: 1.1
Asset Reporting Format Version: 1.1

==== Capabilities added by auto-loaded plugins ====
No plugins have been auto-loaded...

==== Paths ====
Schema files: /usr/share/openscap/schemas
Schematron files: /usr/share/openscap/xsl
Default CPE files: /usr/share/openscap/cpe
Probes: /usr/lib/x86_64-linux-gnu/openscap

==== Inbuilt CPE names ====
I/O warning : failed to load external entity "/usr/share/openscap/cpe/openscap-cpe-dict.xml"

==== Supported OVAL objects and associated OpenSCAP probes ====
system_info                  probe_system_info           
family                       probe_family                
filehash                     probe_filehash              
environmentvariable          probe_environmentvariable   
textfilecontent54            probe_textfilecontent54     
textfilecontent              probe_textfilecontent       
variable                     probe_variable              
xmlfilecontent               probe_xmlfilecontent        
environmentvariable58        probe_environmentvariable58 
filehash58                   probe_filehash58            
dpkginfo                     probe_dpkginfo              
inetlisteningservers         probe_inetlisteningservers  
partition                    probe_partition             
iflisteners                  probe_iflisteners           
selinuxboolean               probe_selinuxboolean        
selinuxsecuritycontext       probe_selinuxsecuritycontext
file                         probe_file                  
interface                    probe_interface             
password                     probe_password              
process                      probe_process               
runlevel                     probe_runlevel              
shadow                       probe_shadow                
uname                        probe_uname                 
xinetd                       probe_xinetd                
sysctl                       probe_sysctl                
process58                    probe_process58             
fileextendedattribute        probe_fileextendedattribute 
routingtable                 probe_routingtable

**Comment by redhatrises** [comment]
Looks like the error is because the `systemd` probes are missing from the scanner.

**Comment by jan-cerny** [comment]
I think the problem is that OpenSCAP 1.0.2 which is shipped in Ubuntu 14.04 doesn't have systemd probes implemented and doesn't support OVAL 5.11, which is required for this benchmark to run.  I suggest updating OpenSCAP on the remote machine to version 1.2.2 or newer.

**Comment by dshiver** [comment]
@redhatrises how would I remedy this?

**Comment by dshiver** [comment]
Thanks all I was able to get this up and running /
