### ISSUE TITLE
Enable ntpd service

### ISSUE THREAD

**Issue by dshiver** [OpenSCAP/scap-workbench#216]
I am showing this error even though ntpd is installed and running.  Anyone know how I may get rid of this from showing in the report? This is what I'm showing as the status

timedatectl status
      Local time: Fri 2018-10-26 18:17:28 UTC
  Universal time: Fri 2018-10-26 18:17:28 UTC
        RTC time: Fri 2018-10-26 18:17:27
       Time zone: Etc/UTC (UTC, +0000)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no

**Comment by redhatrises** [comment]
@dshiver can you provide more info? These type of issues are hard to even know what's wrong when
there isn't much detail. Also, do you get more info when you add `--oval-results` as part of your scan?

**Comment by dshiver** [comment]
Sure so I am running this on Ubuntu 16.04 using scap-workbench.  The profile used is "Common Profile for General Purpose Ubuntu Systems" when I run and show report I am seeing only one high rated rule in my report (see attached)
<img width="1209" alt="screen shot 2018-10-26 at 11 32 45 am" src="https://user-images.githubusercontent.com/25825726/47585824-4e88e300-d913-11e8-9543-7d5f383c67c4.png">

**Comment by dshiver** [comment]
@redhatrises ^

**Comment by dshiver** [comment]
apt-cache policy ntp
ntp:
  Installed: 1:4.2.8p4+dfsg-3ubuntu5.9
  Candidate: 1:4.2.8p4+dfsg-3ubuntu5.9
  Version table:
 *** 1:4.2.8p4+dfsg-3ubuntu5.9 500
        500 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
        100 /var/lib/dpkg/status
     1:4.2.8p4+dfsg-3ubuntu5 500
        500 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial/main amd64 Packages

**Comment by dshiver** [comment]
apt-cache policy ntp
ntp:
  Installed: 1:4.2.8p4+dfsg-3ubuntu5.9
  Candidate: 1:4.2.8p4+dfsg-3ubuntu5.9
  Version table:
 *** 1:4.2.8p4+dfsg-3ubuntu5.9 500

**Comment by dshiver** [comment]
systemctl status ntp
● ntp.service - LSB: Start NTP daemon
   Loaded: loaded (/etc/init.d/ntp; bad; vendor preset: enabled)
   Active: active (running) since Fri 2018-10-26 22:27:38 UTC; 6s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 9742 ExecStop=/etc/init.d/ntp stop (code=exited, status=0/SUCCESS)
  Process: 9754 ExecStart=/etc/init.d/ntp start (code=exited, status=0/SUCCESS)
    Tasks: 2
   Memory: 656.0K
      CPU: 16ms
   CGroup: /system.slice/ntp.service
           └─9770 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 112:116

**Comment by MarkMangoba** [comment]
@redhatrises bump - working with @dshiver here.

**Comment by redhatrises** [comment]
@MarkMangoba @dshiver need `results.xml`, `results.html`, and DEVEL output from scan. 

`oscap xccdf eval --verbose DEVEL --profile my_profile --rule xccdf_org.ssgproject.content_rule_service_ntpd_enabled --results results.xml --report results.html --oval-results my_ds.xml`

**Comment by dshiver** [comment]
@redhatrises do you have an email that we can send these files to?

**Comment by redhatrises** [comment]
@dshiver you should be able to upload them here.

**Comment by redhatrises** [comment]
@dshiver can you upload the files to this PR?

**Comment by redhatrises** [comment]
Closing as the requested information has not been provided. Please reopen with the requested information.
