### ISSUE TITLE
Ubuntu 18.10 new install scap greyed out

### ISSUE THREAD

**Issue by just4bs** [OpenSCAP/scap-workbench#220]
New install of 18.10 and is recently updated. I installed workbench with the standard line "apt-get install scap-workbench". I turn it on and everything is greyed out. I've used this before a year ago, so I don't know if I'm not remembering something.

**Comment by just4bs** [comment]
New install of 18.10 and is recently updated.  I installed workbench with the standard line "apt-get install scap-workbench".  I turn it on and everything is greyed out.  I've used this before a year ago, so I don't know if I'm not remembering something.

**Comment by just4bs** [comment]
Here is the screenshot from the install and operation.  Here is the only error I see on syslog.   I ran it again to look directly for some new errors, but none showed.  
Dec 10 14:55:34 dave-laptop gnome-software[3116]: failed to rescan: No valid root node specifiedDec 10 14:55:34 dave-laptop gnome-software[3116]: failed to rescan: Failed to parse /usr/share/applications/scap-workbench.desktop file: cannot process file of type application/x-desktopDec 10 14:55:39 dave-laptop gnome-software[3116]: Only 1 apps for recent list, hidingDec 10 14:55:41 dave-laptop PackageKit: resolve transaction /45_badbeaae from uid 1000 finished with success after 498ms
If you need something else, let me know.  I'm curious to what happened here.
-Dave  

    On Sunday, December 9, 2018, 12:28:09 PM EST, Matěj Týč <notifications@github.com> wrote:  
 
 
Hello, please try to execute scap-workbench from the terminal, and check out for potential error messages. Also, a screenshot could help.

**Comment by matejak** [comment]
Please attach the screenshot to the issue, or post a link to a picture sharing site. e-mail attachments don't work here on Github issues.

**Comment by DavidCA916** [comment]
Same issue, no errors.
![scapubuntu18](https://user-images.githubusercontent.com/413213/57740401-8ddb0f00-766c-11e9-94aa-0e54c5e6bf61.PNG)

**Comment by cipherboy** [comment]
Closing this in favor of #252.
