### ISSUE TITLE
Search works only in selected sub-trees

### ISSUE THREAD

**Issue by zemb** [OpenSCAP/scap-workbench#24]
Let's say I use RH CCP profile from RHEL-7 XCCDF.
When I search for "encrypt", it finds "Encrypt Transmitted Data Whenever Possible" and "Encrypt Partitions".
But if I deselect "Introduction" the "Encrypt Transmitted Data Whenever Possible" under "Introduction" is not found when doing the search.

**Comment by ybznek** [comment]
@mpreisler I think it is caused by `disabled` tree elements - cannot be focused . Did you have any reason why they are disabled and not only `unchecked`?

**Comment by ybznek** [comment]
Fixed by https://github.com/OpenSCAP/scap-workbench/issues/73
