### ISSUE TITLE
Non intuitive "Close currently opened file" dialog text

### ISSUE THREAD

**Issue by dahaic** [OpenSCAP/scap-workbench#25]
Hello,
I have two proposals for changes to that dialog:

1. Usually when such dialog is presented to the user, it contains positive type of question, like:
`Do you want to proceed?` with explanation what proceeding consists of provided beforehand. Asking if user wants to close file feels like negative question and thus a bit harder to understand.

2. User may be more interested in identifying which file is being closed, than what file (s)he wants to open, as (s)he selected it just few seconds earlier.

**Comment by b-long** [comment]
:+1: I agree, certainly a fan of anything to improve user experience

**Comment by mpreisler** [comment]
Fixed by #38
