### ISSUE TITLE
Option 'Fetch remote resources' is displayed and available for use while target is a local machine

### ISSUE THREAD

**Issue by Ricky-Tigg** [OpenSCAP/scap-workbench#255]
**Component/OS**: scap-workbench.x86_64 1.2.1-2.fc32 @fedora; compiled with Qt 5.13.2, using OpenSCAP 1.3.2

Option _Fetch remote resources_ is displayed and available for use while the target is _Local Machine_. Probably it is aimed to not be so in that case.

![scap-workbench_v 1 2 1_local_machine](https://user-images.githubusercontent.com/26058215/77569516-fde43380-6ed2-11ea-88a0-5da04af8cba8.png)

**Comment by redhatrises** [comment]
@Ricky-Tigg this is expected behavior. In this case, the content pulls down remote CVE OVAL feed.

**Comment by Ricky-Tigg** [comment]
Tool-tip tied to that option:

![workbench_1 2 1_fetch-remote_resources_tool-tip](https://user-images.githubusercontent.com/26058215/77623690-358dc280-6f49-11ea-887f-ff3f6d68cd64.png)

I might have misinterpreted the context if not the key-words upon winch the present report was sent. In the expression "_download of remote_"  _download_ implicitly refers to _download from_ and _remote_ implicitly refers to _remote resource_.

**Comment by evgenyz** [comment]
@Ricky-Tigg What change you are suggesting, exactly?

**Comment by Ricky-Tigg** [comment]
```
$ man oscap
--fetch-remote-resources
Allow download of remote components referenced from Datastream.
```
Output while that option is selected alone along with _Dry run_:

`oscap xccdf eval --fetch-remote-resources --datastream-id scap_org.open-scap_datastream_from_xccdf_ssg-fedora-xccdf-1.2.xml --xccdf-id scap_org.open-scap_cref_ssg-fedora-xccdf-1.2.xml --profile xccdf_org.ssgproject.content_profile_ospp --oval-results --results /tmp/xccdf-results.xml --results-arf /tmp/arf.xml --report /tmp/report.html /tmp/scap-workbench-ChfcwQ/ssg-fedora-ds.xml`

Tha very command did not require from user any interaction that would achieve the task suggested by tool-tip "_download of remote_". It even behaved the same as without the option `--fetch-remote-resources`.

**Comment by evgenyz** [comment]
The option will affect behaviour of the scanner only when DataStream used for scanning would contain some remote resources (like CVE OVAL feed).

**Comment by evgenyz** [comment]
It is absolutely unrelated to the fact that target machine is local or remote. The only thing in common is the very word 'remote', which is unavoidable, I guess.

**Comment by Ricky-Tigg** [comment]
in manual page there is no complementary syntax tied to option `--fetch-remote-resources`; you note it there by yourself  it is mentioned **alone**. No mention indeed referring to "_contain some remote resources (like CVE OVAL feed reference)._".
