### ISSUE TITLE
show notification that opened file was changed

### ISSUE THREAD

**Issue by dahaic** [OpenSCAP/scap-workbench#26]
Button `Scan` scans system based on current version of the file on disk - that I understand is a feature. But user may be confused by that, as it may actually scan something different than what is presented by Workbench in the moment of clicking on the `Scan` button.

Would it be possible to show some kind of notification that source file was altered, so user could reload it? [Or at least passively acknowledge it]

**Comment by cipherboy** [comment]
@mpreisler My thoughts on this and #134 are to first copy the scan file to a temporary directory upon loading; `openscap` will then run against that version. When the application is closed, it can remove all temporary files.

We can then use the [FS Watcher](http://doc.qt.io/qt-5/qfilesystemwatcher.html) on the original file and notify of it changing and prompt to reload it.

**Comment by cipherboy** [comment]
Fixed by #177.
