### ISSUE TITLE
U_MS_Windows_10_V2R1_STIG_SCAP_1-2_Benchmark.xml run on Windows 10

### ISSUE THREAD

**Issue by kazuyalb** [OpenSCAP/scap-workbench#272]
I run oscap with below options
oscap xccdf eval --verbose DEVEL --verbose-log-file log.txt  --results result.xml --oval-results --report report.html U_MS_Windows_10_V2R1_STIG_SCAP_1-2_Benchmark.xml

SRG-OS-000076-GPOS-00044 (Accounts must be configured to require password expiration.) was unknown status.

DEVEL Log file

I: installDir\oscap.exe:     Creating new syschar for wmi_object 'oval:mil.disa.stig.windows:obj:7700'. [installDir\oscap.exe(13180):unknown(2c5c):c:\projects\openscap\src\oval\oval_probe.c:135:oval_probe_query_object]
W: installDir\oscap.exe:     OVAL object not supported. [installDir\oscap.exe(13180):unknown(2c5c):c:\projects\openscap\src\oval\oval_probe.c:147:oval_probe_query_object]
I: installDir\oscap.exe:     Test 'oval:mil.disa.stig.windows:tst:7700' requires that none of the objects defined by 'oval:mil.disa.stig.windows:obj:7700' exist on the system. [installDir\oscap.exe(13180):unknown(2c5c):c:\projects\openscap\src\oval\results\oval_resulttest.c:893:_oval_result_test_evaluate_items]
I: installDir\oscap.exe:     0 objects defined by 'oval:mil.disa.stig.windows:obj:7700' exist on the system. [installDir\oscap.exe(13180):unknown(2c5c):c:\projects\openscap\src\oval\results\oval_resulttest.c:902:_oval_result_test_evaluate_items]

Please tell me how to deal with the problem.

OpenSCAP command line tool (oscap) 1.3.0

**Comment by evgenyz** [comment]
It is a problem of the OpenSCAP scanner itself: https://github.com/OpenSCAP/openscap/issues/1674. There is nothing you can do about it except implementing missing probes.

**Comment by evgenyz** [comment]
See also `windows` tag in issues.
