### ISSUE TITLE
SCAP Workbench 1.1.0 - Inconsisten benchmark names in the "Open SCAP Security Guide" dialog

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-workbench#28]
Description of problem:

SCAP Workbench of version 1.1.0 and earlier does not use a consistent way in order to name
button labels in the "Open SCAP Security Guide" dialog (some benchmarks are titled with first letter capitalized, some benchmarks labels are completely in lowercase).

Version:
scap-workbench-1.1.0-2.el7.centos.x86_64 from isimluk's COPR repository

How reproducible:
Always

Steps to Reproduce:
* run scap-workbench with latest SCAP Security Guide 0.1.24 version installed,
* notice the benchmark labels in the displayed "Open SCAP Security Guide" dialog

Current result:
See the attached image -- some labels have first letter capitalized, while the others are completely in lowercase
![scap-workbench-1 1 0-screenshot](https://cloud.githubusercontent.com/assets/8414918/8618257/98f66852-270c-11e5-8b10-0927e58601a5.png)

Expected result:
Uniform approach when displaying benchmark names - either all labels to be in lowercase, or all of them to have first letter capitalized (maybe 'JRE' is an exception here, and it should have all the letters capitalized).

Additional information:
Also notice the way how SCAP Security Guide logo is displayed -- instead of whole logo, there's top and bottom part of it greyed out. I can file a separate ticket for this if required.

**Comment by mpreisler** [comment]
There are 2 issues that should be fixed as part of this ticket.
* Support more content folders and rewrite them into nicer names - e.g.: `CentOS6` instead of `centos6`, `JRE` instead of `jre`, ... - this is relatively trivial
* Pack all the buttons into a scrollarea so that it scales better. When this dialog was created I didn't envision `SSG` shipping so much content, I greatly underestimated the speed at which the project progressed in the past few months :-) - this requires a bit of `Qt4` knowledge, I am willing to mentor

**Comment by iankko** [comment]
Thanks, Martin.

Could within the proposed changes be assured that the widget displaying SCAP Security Guide logo is large enough to hold the whole logo? IOW ensure it's not cut off like in actual version.

Thanks, Jan.

**Comment by mpreisler** [comment]
> Could within the proposed changes be assured that the widget displaying SCAP Security Guide logo is large enough to hold the whole logo? IOW ensure it's not cut off like in actual version.

Definitely, thanks for the comment. Also the text that comes after the logo needs to be displayed fully. All of this layout weirdness is caused by the sheer amount of content folders `SSG` now ships :-)

**Comment by mpreisler** [comment]
Thanks @ybznek !
