### ISSUE TITLE
Error Project Compilation on QT5 1.2.1

### ISSUE THREAD

**Issue by jkljkl1197** [OpenSCAP/scap-workbench#283]
Hi, i have a problem with deprecated code while compiling under Parrot Debian Linux

here the log:
[  2%] Built target docs
[  4%] Automatic MOC for target scap-workbench
[  4%] Built target scap-workbench_autogen
Scanning dependencies of target scap-workbench
[  6%] Building CXX object CMakeFiles/scap-workbench.dir/src/TailoringWindow.cpp.o
/home/parrot/scap-workbench-1.2.1/src/TailoringWindow.cpp: In member function ‘void TailoringWindow::deserializeCollapsedItems()’:
/home/parrot/scap-workbench-1.2.1/src/TailoringWindow.cpp:648:40: error: ‘static QSet<T> QSet<T>::fromList(const QList<T>&) [with T = QString]’ is deprecated: Use QSet<T>(list.begin(), list.end()) instead. [-Werror=deprecated-declarations]
  648 |     mCollapsedItemIds = QSet<QString>::fromList(list);
      |                                        ^~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qitemselectionmodel.h:45,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractitemview.h:46,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qheaderview.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QHeaderView:1,
                 from /home/parrot/scap-workbench-1.2.1/build/ui_TailoringWindow.h:15,
                 from /home/parrot/scap-workbench-1.2.1/include/TailoringWindow.h:37,
                 from /home/parrot/scap-workbench-1.2.1/src/TailoringWindow.cpp:22:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h:416:9: note: declared here
  416 | QSet<T> QSet<T>::fromList(const QList<T> &list)
      |         ^~~~~~~
/home/parrot/scap-workbench-1.2.1/src/TailoringWindow.cpp:648:53: error: ‘static QSet<T> QSet<T>::fromList(const QList<T>&) [with T = QString]’ is deprecated: Use QSet<T>(list.begin(), list.end()) instead. [-Werror=deprecated-declarations]
  648 |     mCollapsedItemIds = QSet<QString>::fromList(list);
      |                                                     ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qitemselectionmodel.h:45,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractitemview.h:46,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qheaderview.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QHeaderView:1,
                 from /home/parrot/scap-workbench-1.2.1/build/ui_TailoringWindow.h:15,
                 from /home/parrot/scap-workbench-1.2.1/include/TailoringWindow.h:37,
                 from /home/parrot/scap-workbench-1.2.1/src/TailoringWindow.cpp:22:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h:416:9: note: declared here
  416 | QSet<T> QSet<T>::fromList(const QList<T> &list)
      |         ^~~~~~~
/home/parrot/scap-workbench-1.2.1/src/TailoringWindow.cpp: In member function ‘void TailoringWindow::serializeCollapsedItems()’:
/home/parrot/scap-workbench-1.2.1/src/TailoringWindow.cpp:660:83: error: ‘QList<T> QSet<T>::toList() const [with T = QString]’ is deprecated: Use values() instead. [-Werror=deprecated-declarations]
  660 |         mQSettings->setValue(getQSettingsKey(), QVariant(mCollapsedItemIds.toList()));
      |                                                                                   ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qitemselectionmodel.h:45,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qabstractitemview.h:46,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qheaderview.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QHeaderView:1,
                 from /home/parrot/scap-workbench-1.2.1/build/ui_TailoringWindow.h:15,
                 from /home/parrot/scap-workbench-1.2.1/include/TailoringWindow.h:37,
                 from /home/parrot/scap-workbench-1.2.1/src/TailoringWindow.cpp:22:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h:265:14: note: declared here
  265 |     QList<T> toList() const { return values(); }
      |              ^~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/scap-workbench.dir/build.make:450 : CMakeFiles/scap-workbench.dir/src/TailoringWindow.cpp.o] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:125 : CMakeFiles/scap-workbench.dir/all] Erreur 2
make: *** [Makefile:171 : all] Erreur 2

I try to find a fix but, i am not that good in c++ so i request some help here

Have a nice day, and if you have a .deb package (for qt5) to share instead of building it myself, give me a link Thanks.

**Comment by matejak** [comment]
Very likely fixed by #259, please reopen if it is not the case.
