### ISSUE TITLE
[RFE] SCAP Workbench -- Add support for ```--fetch-remote-resources``` oscap option

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-workbench#29]
Description of problem:
The ```oscap``` tool provides ```--fetch-remote-resources``` command line option in order to instruct the scanner to download of remote OVAL content referenced from XCCDF by check-content-ref/@href.

SCAP Workbench tool does not provide a possibility how to pass this option to the underlying ```oscap``` process, when performing the system scan.

It would be great if SCAP Workbench could be enhanced to support this option (in GUI, in CLI, or in both - will keep this decision the SCAP Workbench upstream to decide where it would be the most appropriate place to implement this. I am fine with any of the places under assumption that options is reachable somehow).

Thank you for consideration, Jan.

**Comment by mpreisler** [comment]
I think this is not an option for power-users only but also for regular users. Therefore I would prefer a GUI way to enable or disable fetching remote resources.

**Comment by mpreisler** [comment]
Done in #37 by @ybznek
