### ISSUE TITLE
Package for scap-workbench (ubuntu) only available on 18.04 LTS

### ISSUE THREAD

**Issue by capactiyvirus** [OpenSCAP/scap-workbench#290]
I cant apt-get install scap-workbench on 20.04LTS

**Comment by capactiyvirus** [comment]
https://packages.ubuntu.com/search?keywords=scap&searchon=names&suite=all&section=all

**Comment by KennthStailey** [comment]
The Ubuntu 20.04 release of the package is out-of-date and relies on qt4 which is not supported on Ubuntu 20.04 (only qt5 is) so it fails to build.  The source for the (currently) last deb package for Ubuntu is here:
https://launchpad.net/ubuntu/+source/scap-workbench

There is a Debian bug report indicating the Debian experimental repo has scap-workbench 1.2.1 which is current:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=992020

The changelog messages for that Debian package are here:
https://salsa.debian.org/debian/scap-workbench/-/blob/debian/sid/debian/changelog

**Comment by matejak** [comment]
We can't do anything about this here, it's up to distros to take proper care of updating packages. I suggest that you get in touch with respective maintainers to figure out what to do. I will close the issue, as it is not something that we can influence here upstream.

**Comment by JOduMonT** [comment]
> We can't do anything about this here, it's up to distros to take proper care of updating packages. I suggest that you get in touch with respective maintainers to figure out what to do. I will close the issue, as it is not something that we can influence here upstream.

You could at least give the proper information on the website
https://www.open-scap.org/download/
> where You can install SCAP Workbench on **Ubuntu 17.04 (and newer)** using apt-get:  apt-get install scap-workbench 
is obviously wrong

**Comment by ggbecker** [comment]
> > We can't do anything about this here, it's up to distros to take proper care of updating packages. I suggest that you get in touch with respective maintainers to figure out what to do. I will close the issue, as it is not something that we can influence here upstream.
> 
> While on the official website, when we ask to report a bug/open a ticket it land us here (on the repo)
> 
> ![image](https://user-images.githubusercontent.com/5204724/158090187-0598ba16-0df9-4aa4-aeb1-c423cd617d56.png)

You probably want to contact @dodys to ask for something related to newer versions scap-workbench availability. In the meantime you can always try to build yourself using these instructions: https://askubuntu.com/a/1308105

> 
> You could at least give the proper information on the website https://www.open-scap.org/download/
> 
> > where You can install SCAP Workbench on **Ubuntu 17.04 (and newer)** using apt-get:  apt-get install scap-workbench
> 
> is obviously wrong

I've updated the page to mention that it only works until 18.04 `SCAP Workbench on Ubuntu 17.04 (and newer until 18.04)`

**Comment by dodys** [comment]
Yeah, Debian dropped scap-workbench a few years ago, but I don't remember the reason for it. Consequently this also was removed from Ubuntu.
Nonetheless, there's someone trying to push scap-workbench again to the debian repos (currently on experimental) which you can check here: https://tracker.debian.org/pkg/scap-workbench and another person built it for Ubuntu 20.04: https://launchpad.net/~metta-crawler/+archive/ubuntu/scap-workbench/+packages . Please be aware that this is a person's PPA and not maintained at all by Canonical, so it is your own risk to install such package.
In the meantime I will forward your concerns internally to see if we can get scap-workbench back to Ubuntu official repos.
