### ISSUE TITLE
Translation | README file  | Relevant methodology needed

### ISSUE THREAD

**Issue by Ricky-Tigg** [OpenSCAP/scap-workbench#292]
**version:** 1.2.1; **Tested on:** Fedora; **Kernel:** v.5.14

```
$ rpm -ql scap-workbench | grep -E '.xml$|translation'
/usr/share/appdata/scap-workbench.appdata.xml
/usr/share/scap-workbench/translations/README
$ cat  /usr/share/scap-workbench/translations/README
Translations created using QtLinguist go into this folder.
```
**Project:** creation of translation file

Hello,  This _appdata.xml_ file is the unique installed file containing strings covering the texts exhibited in this application's interfaces.  Therefore it is most likely to be the file against which a translation file would be created.  Though in that _README,_ as you can noticed it by yourself, a complete and up-to-date methodology to achieve a creation of such file is missing.  In the meanwhile, is there any relevant information that would be worth a mention here?

**Comment by Ricky-Tigg** [comment]
It sounds that adaptation would be a task where solely developers have power upon  if my interpretation is correct. I had figured out by investigating on [Qt](https://doc.qt.io/qt-5/linguist-manager.html)'s side that  it could be so. Is it premature to close as i wonder if there might be sufficient resources in this project to achieve that goal?

**Comment by Ricky-Tigg** [comment]
It sounds that adaptation would be a task where solely developers have power over if my interpretation is correct. I had figured out by investigating on [Qt](https://doc.qt.io/qt-5/linguist-manager.html)'s side that it could be so.

**Comment by Ricky-Tigg** [comment]
You noticed like i did that the state of the present request has been left pending for more than a decent period, which is certainly not fair to you. Would it be so that no one beyond the contributors with the required skill for conducting a review was willing to review your contribution or is it that no one yet could do so as no one has even been reached by you or anyone else in this regard?.

**Comment by Ricky-Tigg** [comment]
You may have noticed, as i did, that the state of your request has been left pending for more than a decent period, which is certainly not fair to you. Would it be so that no one beyond the contributors with the required skill for conducting a review was willing to review your contribution or is it that no one yet could do so as no one has even been reached by you or anyone else in this regard?.

**Comment by ggbecker** [comment]
Unfortunately there was no interest in the community to make things go forward with that pull request as it is not on the priority list.

I will check if someone can take a look at that to at least have the basis for translation support.
