### ISSUE TITLE
Revisit openUrl on Gnome 3

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/scap-workbench#3]
For some users it doesn't do anything and returns success... 

Original trac ticket: https://fedorahosted.org/scap-workbench/ticket/293

**Comment by mpreisler** [comment]
Tested with Fedora 21 with GNOME 3 and it works :-/

**Comment by WesleyCeraso** [comment]
@mpreisler Should we keep this ticket?

**Comment by mpreisler** [comment]
I have no idea to be honest, I could never reproduce this issue but multiple users reported it.

**Comment by matejak** [comment]
This issue now doesn't have a description, the trac ticket is not valid any more.

**Comment by jan-cerny** [comment]
@mpreisler Do you remember what it was about? The trac on fedorahosted.org is no longer available. If not, please close this issue.

**Comment by cipherboy** [comment]
To my knowledge, all openUrls work, particularly of the user manual, generated user guide, and the report file. I'm closing this; if anyone wishes to reopen it, please do so. :)
