### ISSUE TITLE
Ansible remediation for systemd-journald has invalid syntax because of quotation marks

### ISSUE THREAD

**Issue by Maddss** [OpenSCAP/scap-workbench#315]
When generating an Ansible remediation script using the SCAP workbench there seems to be invalid syntax in systemd-journald configuration:
xccdf_org.ssgproject.content_rule_journald_compress
xccdf_org.ssgproject.content_rule_journald_forward_to_syslog
xccdf_org.ssgproject.content_rule_journald_storage

For Example:
line: ForwardToSyslog="yes" should be ForwardToSyslog=yes without quotation marks
This breaks the remediation as the settings don't work with quotation marks. 
OpenSCAP scanner also checks these settings without quotation marks and returns them as failed.

tags:
CCE-85931-4
CCE-85996-7
CCE-86046-0

**Comment by evgenyz** [comment]
The remediations themselves belong to CaC project (ssg). This is the place to open an issue: https://github.com/ComplianceAsCode/content/issues. (Please follow the template and fill all the information required to identify the problem).
