### ISSUE TITLE
[RFE / bug] Automatically enable parent XCCDF group in the tailoring window, if the child node is selected (when "Deselect all" option was used before)

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-workbench#36]
scap-workbench (version 1.1.0) in the tailoring window does not automatically enables parent XCCDF group in the benchmark as selected, if child XCCDF rule (node) is selected.

Reproducible:
Always

Affected versions:
1.1.0 and below (didn't try current master)

How to reproduce:
1) Open some SCAP content in scap-workbench (will describe the process on SSG content for Fedora)
2) Select 'common' profile && click customize. Click 'Ok' on the next dialog displayed, this should take you to the main tailoring dialog,
3) Click "Deselect all" button / option && see how all the rules are deselected,
4) Now select some unselected group, check in the check-box next to it, and select also some child rule (deeper than one level in the tree). Check in the check-box next to that rule.
5) Click 'Confirm Changes' button

Actual result:
No rule is selected in the scap-workbench main window.

Expected result:
The selected child node / rule should be displayed in the main scap-workbench window.

Additional information:
Concrete scenario for 'Disable snmpd Service rule' is below:
1) Open 'Common Profile for General-Purpose Fedora Systems' Fedora SSG profile in scap-workbench,
2) Click 'Customize' button,
3) Click 'OK' when prompted for new profile ID etc.,
4, Click 'Deselect All' button,
5, Go to 'Services', enable 'SNMP Server' tree part, enable the 'Disable snmpd Service' rule too
6, Click 'Confirm changes'

Actual result:
Watch  how XCCDF Subgroup 'Disable SNMP Server if Possible' is group is not selected, and therefore 'Disable snmpd Service' rule is not selected either, and after clicking 'Confirm changes' there's no rule visible in scap-workbench's main window.

Expected result:
Selecting / checking in a main XCCDF group, and a rule within it, should also automatically checking all the parent groups, that are necessary in order to the final child rule to be included into the tailoring file (once Deselect All option has been used).

Not sure if this is bugfix / RFE, thus used both of them in the report.

Thank you for looking into this!

Jan

**Comment by iankko** [comment]
Screenshot of the issue (SW situation after clicking 'Deselect All' option and right before clicking the 'Confirm changes' button). Notice how ```Disable SNMP Server if Possible``` rule is not selected (arrow points to it), and it should be IMHO, when the parent rule, and some of the children is selected. It should be because current approach requires all parents of the particular node (except the highest one) to be manually checked-in if the user wanted the rule to be selected.
<br/> <br/>

![sw_screenshot](https://cloud.githubusercontent.com/assets/8414918/9332247/0d58192c-45c4-11e5-839a-e955e3e4f259.png)

<br/> <br/>

**Comment by yuumasato** [comment]
Fixed by #113.
