### ISSUE TITLE
[RFE] Hide 'default' profile if it does not contain some selected rules

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-workbench#40]
`scap-workbench` currently provides listing of profiles present in the benchmark, that can be selected to be used to scan the system in question. The `default` profile is exceptional in this context. Exceptional in the sense, it's not present in every benchmark, and it's required by the SCAP standard to be provided "artificially" by the scanner. The motivation behind this requirement being that `default` profile it's intended to contain all rules (if no more specific XCCDF profile is selected).

Though in the context of SCAP Security Guide project the `default` profile is not used (the `default` profiles contains no rules selected). Therefore for SCAP Security Guide purpose the `default` profile is of very limited use (one use case coming to mind is to select `default` profile to have empty benchmark, then use tailoring to select just couple of rules to be scanned).

Therefore this RFE is to request the `default` profile to be shown in the listing of available `scap-workbench` profiles only in the case the `default` profile provided from the content truly contains some of the rules being selected (e.g. it would not be displayed if it does not contain some selected rules).

Thank you, Jan.

**Comment by mpreisler** [comment]
There is a common use-case that requires the `(default)` profile, user selects it, then clicks `Customize` and then selects a few rules. This is more or less equivalent to creating a new profile from scratch.

Would you be happy with SCAP Workbench listing how many rules are selected for each of the profile in the combobox? The `(default)` profile would still be available there but users would immediately see that it is empty.

**Comment by ybznek** [comment]
Count of rules in brackets could be great, IMHO.

@yuumasato  What is your opinion?

**Comment by yuumasato** [comment]
I would suggest the use of parenthesis instead of brackets.

Considering the use case in which user starts to customize from an empty profile. How would the user do this if  the `(default)` profile is not empty?

Along with the count of rules, would it be interesting to add an `(empty)` profile when the `(default)` profile has rules selected?

**Comment by ybznek** [comment]
> I would suggest the use of parenthesis instead of brackets.

I agree.

>Along with the count of rules, would it be interesting to add an (empty) profile when the (default) profile has rules selected?

In SSG we don't have selected rules in "default" profile, but IMHO (empty) profile could be useful for some contents.

**Comment by mpreisler** [comment]
> Considering the use case in which user starts to customize from an empty profile. How would the user do this if the (default) profile is not empty?

The default profile is always the starting point and it is always empty in the sense that it has no `select` elements. It will have some rules in it if those rules are selected by default - their `selected` attribute is true in their Rule elements.

The user can create a new profile and unselect some of these rules by clicking `Unselect All` in the tailoring window.

> In SSG we don't have selected rules in "default" profile, but IMHO (empty) profile could be useful for some contents.

I disagree and I think it would complicate the implementation if we introduced another meta-profile. `(default)` is mandated by the XCCDF standard and gives us enough problems as it is.

**Comment by yuumasato** [comment]
> The user can create a new profile and unselect some of these rules by clicking Unselect All in the tailoring window.

That's true, there is no need for an `(emtpy)` profile.
