### ISSUE TITLE
[RFE] Add ability to specify remotely located XCCDF file accessible behind the http:// or https:// protocols

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-workbench#44]
Description of problem:
Specifying e.g.:

```
$ scap-workbench http://www.redhat.com/security/data/metrics/com.redhat.rhsa-all.xccdf.xml
```

Displays the error dialog with the following content:

```
17:40:01 info        SCAP Workbench 1.1.0, compiled with Qt 4.8.6, using OpenSCAP 1.2.5
17:40:01 except   Error while opening file. There was a problem with ScanningSession! Failed to create session for 'http://www.redhat.com/security/data/metrics/com.redhat.rhsa-all.xccdf.xml'. OpenSCAP error message: Unable to parse XML at: $CWD/http:/www.redhat.com/security/data/metrics/com.redhat.rhsa-all.xccdf.xml' [oscap_source.c:187]
```

where `$CWD` corresponds to current working directory on the target system, which scap-workbench has been launched from.

Therefore it would be very nice if XCCDF benchmarks to scan the system in question against could be specified also in the form of (commonly used) http:// or https:// protocols on the scap-workbench command line.

Thank you, Jan.

Additional information:
The expectation in this RFE being that if such a XCCDF file specified via http:// or https:// URLs would reference a corresponding OVAL document (like in the first example above), that OVAL document would be downloaded too (in order the system scan against that benchmark to be successful).

**Comment by jan-cerny** [comment]
We already have --fetch-remote-resources feature in oscap.

This feature would be useful if we have CVE scan button.

The users can always download and save their content on hard drive.
