### ISSUE TITLE
[RFE] Add support for processing OVAL formatted files

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-workbench#45]
Description of problem:
`SCAP-Workbench` currently does not support loading of an OVAL formatted file and performing a system scan based on it. Though the underlying `oscap` tool supports e.g. evaluating of OVAL documents, or collecting system characteristics based on OVAL documents. Relevant `oscap` commands are as follows (from the `oscap(8)` manual page):

```
OVAL OPERATIONS
       eval [options] INPUT_FILE
              Probe the system and evaluate all definitions from OVAL Definition file. Print result of each 
             definition to standard output. The return  code  is  0 after a  successful evaluation. On error, 
             value 1 is returned.
..
       collect [options] definitions-file
              Probe the system and gather system characteristics for all objects in OVAL Definition file.
..
      analyse [options] --results FILE definitions-file syschar-file
              In  this mode, the oscap tool does not perform data collection on the local system, but 
              relies upon the input file, which may have been generated on another system. The output
              (OVAL Results) is printed to file specified by --results parameter.
..
      validate [options] oval-file
              Validate given OVAL file against a XML schema. Every found error is printed to the 
             standard error. Return code is 0 if  validation  succeeds,  1  if validation could not be
             performed due to some error, 2 if the OVAL document is not valid.
..
      generate <submodule> [submodule-specific-options]
              Generate another document form an OVAL file.
..
      list-probes [options]
              List supported object types (i.e. probes)
```

Of course not all of the OVAL operations supported / provided by `oscap` would be necessary to be implemented at the beginning. For the start it would be sufficient if `SCAP-Workbench` would be able to open an OVAL file (not to display an error dialog after opening it by mistake), and possibly to perform OVAL evaluation and / or OVAL system characteristics collections tasks.

Thank you for consideration this feature.

Jan.

**Comment by jan-cerny** [comment]
We prefer to use Datastreams. In SCAP 1.2, the recomended way to distribute the content is a datastream. It would be very difficult to support this in SCAP Workbench.
