### ISSUE TITLE
SCAP Workbench was compiled without local scanning support

### ISSUE THREAD

**Issue by manchild73** [OpenSCAP/scap-workbench#48]
When I launch the WorkBench, 'Local Machine' is greyed out.  Hovering over the radio button shows the message: "SCAP Workbench was compiled without local scanning support"

I have installed this onto an iMac running OS X 10.10.5 and would like to scan this machine.

**Comment by mpreisler** [comment]
Hi,
thanks for your ticket! Unfortunately, the local machine radio button is greyed out on purpose. SCAP Workbench is fully portable but uses OpenSCAP for the actual SCAP scans. OpenSCAP only has minimal OSX support. It can be built there but it doesn't support any of the darwin/OSX OVAL tests. My intuition is that many of the independent and unix OVAL tests will work on OSX without extensive changes but that hasn't been tested yet.

OSX support isn't the top priority for us in the OpenSCAP team, we are looking for contributors who could help us achieve full OSX support. We would definitely support such efforts.
