### ISSUE TITLE
Non intuitive "profile ID" text edit.

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/scap-workbench#49]
When you want to customize some profile, you can type name of new profile.
If you remove "xccdf_" prefix part, text edit doesn't allow you to type(without any notification), if you don't type "xccdf_"

I think, it would be better if text edit will contain "xccdf_" prefix always and doesn't allow to delete it.

In my opinion, "OK" button should not be enabled if you don't have valid ID. Message when dialog is closed is not user friendly.

**Comment by WesleyCeraso** [comment]
Feature implemented in 1.0.3 (ca435e0e)

**Comment by WesleyCeraso** [comment]
Closed by mistake, reopening.
