### ISSUE TITLE
Errors: No match found for key-sequence

### ISSUE THREAD

**Issue by Oneiroi** [OpenSCAP/scap-workbench#53]
OSX 10.11.1 system running scap-workbench
Targethost is CentOS7 x86_64 

Paste here (GH wouldn't allow it due to the length):
https://paste.fedoraproject.org/293874/ (expires in 1 month)

**Comment by iankko** [comment]
@Oneiroi 
Thank you for your report, David. This rather of being an issue of SCAP Workbench / openscap, seems to be an issue of the underlying content. Will inspect more and let you know the summary / conclusion.

**Comment by Oneiroi** [comment]
@iankko thanks for the acknowledgment.

I've since spun up a Fedora23 VM and can confirm the same issue is present there also.
SCAP Workbench 1.1.0, compiled with Qt 4.8.7, using OpenSCAP 1.2.6

Please let me know if there's anything I can do to assist in getting this resolved.

**Comment by mpreisler** [comment]
@Oneiroi I think it's related more to the target machine. Most likely you are using the latest SCAP Workbench with the latest OVAL 5.11.1 SSG and the CentOS7 machine has openscap that doesn't support it yet. Could you try to enable https://copr.fedoraproject.org/coprs/isimluk/OpenSCAP/ COPR repo and try to evaluate again?

**Comment by Oneiroi** [comment]
@mpreisler tested with the COPR repo (as the CentOS7 is a throwaway VM), and indeed this resolves the issue.

So the issue appears to be that the 

EL7 base packages 1.1.1-3 are not compatible with the workbench 1.1.1 / 1.1.0 at this time, packages from the COPR repo 1.2.6-1 however are.

Looks like either the base packages need to be brought up to date and / or some compatibility documentation made available so that the workstation version can be matched accordingly to the required scanner version.

**Comment by mpreisler** [comment]
@Oneiroi Sorry about the inconvenience, it's a bit of a timing issue. This will all "fix itself" soon, see https://git.centos.org/summary/rpms!openscap
