### ISSUE TITLE
Feature request: Handle 'This content points out to the remote resources. Use `--fetch-remote-resources' option to download them.' oscap's warning message more gracefully

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-workbench#57]
The SSG content recently introduced support for referencing of remotely located OVAL files for certain rules. This feature works properly when used with both:
- the `oscap` tool, and
- the `scap-workbench` tool.

But when the `[] Fetch remote resources` checkbox is not checked-in in SCAP Workbench when scanning current e.g. `Common` profile for `RHEL/6` product, the following warning dialog is shown in SCAP Workbench:

![sw_screenshot](https://cloud.githubusercontent.com/assets/8414918/11978663/95c82efa-a98d-11e5-9f26-8d1ffc70bd03.png)
## Current result:

While it's expected SCAP Workbench to show a warning if `Fetch remote resources` option is not checked in, and particular benchmark references a remotely located OVAL, the current form of the provided dialog suggests an error occurred during the system scan. This is not the case (just the `Fetch remote resources` option was not checked in, thus rules referencing remote OVAL will return `notchecked` as a result, instead of actually performing the OVAL evaluation for that rule).
## Expected result:

The warning dialog is displayed in some better looking way (the case when `Fetch remote resources` option is not being checked in, and XCCDF referencing remotely located OVAL use case is handled more gracefully).
## Version of SCAP Workbench tested the issue at:

scap-workbench-1.1.1-1.el6.x86_64

**Comment by yuumasato** [comment]
This has been fixed in #82.
![screenshot from 2016-11-18 17-09-38](https://cloud.githubusercontent.com/assets/7460169/20436855/02cb7f88-adb2-11e6-806d-ff0d84342064.png)
But versions 1.0.x still have this issue.
