### ISSUE TITLE
Provide used command-line arguments

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/scap-workbench#58]
I think it is useful and easy to implement.
When we provide used ```oscap``` arguments to diagnostics window, it can help to inexperienced users to understand the arguments.

**Comment by b-long** [comment]
:+1:

**Comment by iankko** [comment]
@ybznek 
> I think it is useful and easy to implement.

The proposal sounds reasonable to me too (could be great improvement).

Thanks, Jan.

**Comment by jan-cerny** [comment]
@ybznek +1

**Comment by mpreisler** [comment]
+1

We already have this reported on fedorahosted.org I think. Definitely a good idea and should be very simple to implement.

**Comment by mpreisler** [comment]
Implemented in c9f9b9729b50d8d7f4fd3fd27f4388cbb07b4f83

This was not as easy as I expected

**Comment by ybznek** [comment]
Thank you, Martin!
