### ISSUE TITLE
Missing Ubuntu package 

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/scap-workbench#59]
We have mentioned possibility to install scap-workbench on ubuntu/debian using **apt-get**
http://www.open-scap.org/tools/scap-workbench/ 

One user on mailing-list have problem with installing of this package. When I list Ubuntu packages http://packages.ubuntu.com/search?arch=any&searchon=names&keywords=scap-workbench there is no such packages. In ubuntu container I am not able to install it too ```apt-get install scap-workbench```.

Is this incorrect information on portal? Or we are waiting for something?

**Comment by jan-cerny** [comment]
I also haven't found this package, neither in Ubuntu nor in Debian.
But I have found this bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=750138
@mpreisler Do you know some more information about Workbench on Debian or Ubuntu?

**Comment by mpreisler** [comment]
It's an ITP package, IIRC Pierre Chiflier was pushing for it to be imported into Debian.

Either way, this is not an upstream SCAP Workbench bug.

**Comment by jan-cerny** [comment]
@mpreisler OK, thanks for info, I agree with you. However, I will open issue against our portal, because we advertise it there :-) https://github.com/OpenSCAP/website/issues/182

**Comment by zzj0402** [comment]
apt-get install scap-workbench
```
Unable to locate package scap-workbench
```
