### ISSUE TITLE
Crash on Windows 10 when opening datastreams

### ISSUE THREAD

**Issue by jeffstoner** [OpenSCAP/scap-workbench#61]
OS: Windows 10
SCAP Workbench: 1.1.1 (stable)

SCAP Workbench launches and only displays the Firefox and Java security guides. If you try to open any other guide (in scap-workbench\ssg) the program crashes.

I am able to open other guides (such as scap-workbench\ssg\ssg-rhel6-ds.xml) but only if I use --skip-valid on the command line.

Once opened, I can customize the guide, and save it (using Save All -> Into a directory.) However, I cannot re-open it at all, even if I use the --skip-valid option on the command line.

Some of the error messages I see:

16:23:04 
info  
SCAP Workbench 1.1.1, compiled with Qt 4.8.6, using OpenSCAP 1.3.0

16:23:19 
except  
Error while opening file.

There was a problem with ScanningSession!
Failed to reload session. OpenSCAP error message:
Schema file 'sds/1.2/scap-source-data-stream_1.2.xsd' not found in path '/usr/i686-w64-mingw32/sys-root/mingw/share/openscap/schemas' when trying to validate 'C:/Users/jstoner/Documents/Cloud/Projects/CloudManager/SCAP/ssg-rhel6-ds.xml' [validate.c:99]
Invalid SCAP Source Datastream (1.2) content in C:/Users/jstoner/Documents/Cloud/Projects/CloudManager/SCAP/ssg-rhel6-ds.xml. [oscap_source.c:266]
Invalid SCAP Source Datastream (1.2) content in C:/Users/jstoner/Documents/Cloud/Projects/CloudManager/SCAP/ssg-rhel6-ds.xml [xccdf_session.c:469]

**Comment by WesleyCeraso** [comment]
Fixed by OpenSCAP/openscap#770
