### ISSUE TITLE
[RFE/Bugfix] Change default opening window when content is detected

### ISSUE THREAD

**Issue by redhatrises** [OpenSCAP/scap-workbench#66]
When opening scap-workbench with scap-security-guide installed, a window is opened allowing the user to select detected scap-security-guide content. While this window is nice/handy, as more content gets added (say 25 entries or more), this window becomes cluttered and could become unusable if it expands beyond the screen's resolution.

We need to do some sort of combination of the following:

 * Refactor the window to handle hundreds of entries. Maybe a scrollable selection window?
 * Just don't prompt the user to select automatically detected scap-security-guide content and open to a disabled main window.

**Comment by ybznek** [comment]
@redhatrises 
Hi, are you talking about this window? ![screenshot_2016-06-27_13-21-31](https://cloud.githubusercontent.com/assets/2564361/16378112/37ed43ea-3c6a-11e6-86cf-015431cb0d80.png)

I have fixed some bug of the windows in https://github.com/OpenSCAP/scap-workbench/pull/31

Now I have added another 50 fake DS files and it is still working well with FullHD & Workbench released in Fedora23.

Please provide more information to reproduce, thank you.

**Comment by redhatrises** [comment]
> @redhatrises
Hi, are you talking about this window? 

@ybznek yes I am.

>I have fixed some bug of the windows in #31

Seems like a very odd UX design to have a scrollbar with buttons rather than a list box. Guess I will close this.
