### ISSUE TITLE
"dry run" checkbox is smaller then others

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/scap-workbench#69]
on Windows 10

I don't know if it should be smaller, but I think it is strange.
![screenshot_2016-07-12_17-05-00](https://cloud.githubusercontent.com/assets/2564361/16772040/edf25da8-4852-11e6-970c-f15399eb323e.png)

**Comment by mpreisler** [comment]
https://github.com/OpenSCAP/scap-workbench/commit/da2cffc228ad95f7aac48c45c5d48b04a7b45339

**Comment by mpreisler** [comment]
https://github.com/OpenSCAP/scap-workbench/commit/da2cffc228ad95f7aac48c45c5d48b04a7b45339
