### ISSUE TITLE
Remote scanning with separate XCCDF and OVAL files

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/scap-workbench#7]
Right now only SDS is supported which is very limiting. Most existing good quality content doesn't use SDS yet.

Original trac ticket: https://fedorahosted.org/scap-workbench/ticket/147

**Comment by mpreisler** [comment]
SSG has an SDS option now which may slightly lower the importance of this ticket.

**Comment by mpreisler** [comment]
I would really like a clarification regarding priorities of this ticket.

This is a very complex issue that would require drastic changes in remote ssh scanning code in scap-workbench. scap-workbench can't get around parsing XCCDF, OVAL and CPE files to figure out dependencies.

I don't think this is a high priority ticket because SSG ships datastreams now, hopefully other content providers will follow. Do we all agree?

EDIT: There are cases where we can't use the original files verbatim on target machine. For example if they have absolute paths referencing OVAL files.

**Comment by mpreisler** [comment]
As per discussion today, this is postponed until 1.1.0.

Content provides are encouraged to ship SDS and users should be encouraged to use it with workbench and/or oscap.

0497b9190f7c534861fea3dfffc3cbb4e7f54219

**Comment by mpreisler** [comment]
Yet again postponed. There is not enough interest to warrant the pain of implementing this.

**Comment by dahaic** [comment]
Sorry, WONTFIX. Use datastream instead. :)
