### ISSUE TITLE
Missing logo ~ github user manual

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/scap-workbench#70]
https://github.com/OpenSCAP/scap-workbench/blob/v1-1/doc/user_manual.adoc

Generated HTML version seems to be ok.

![screenshot_2016-07-13_10-04-35](https://cloud.githubusercontent.com/assets/2564361/16796142/4c88828c-48e1-11e6-8f57-0417ec5edebb.png)

**Comment by mpreisler** [comment]
This is not a bug... Use the generated version.
