### ISSUE TITLE
Can't connect to "Remote machine" using SSH in scap-workbench

### ISSUE THREAD

**Issue by networkr00** [OpenSCAP/scap-workbench#74]
SCAP Workbench 1.1.1

This is the first attempt at using SCAP Workbench to connect via SSH, and I was surprised to see when I populated the target with the IP address of the machine that I wished to scan that it never prompted me for a password.  Is there a requirement that I put the password somewhere I may have overlooked, like in the target entry line?

Steps to reproduce:

Open scap-workbench as root user on scanner machine (centOS 6.8)
select profile: STIG for RHEL 7 Server, or any other RHEL 7
select target:  root@IP address of RHEL 7 machine I can ssh into and wish to scan
hit 'scan' button

Message at bottom of GUI shows the following and the program hangs indefinitely:

Establishing connecting to remote target...

14:38:05 
info  
SCAP Workbench 1.1.1, compiled with Qt 4.6.2, using OpenSCAP 1.2.8

14:38:11 
info  
Opened file '/usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml'.

14:38:27 
info  
Establishing connecting to remote target...

14:38:27 
error  
Can't connect to remote machine! Exception was: There was a problem with SshConnection! Failed to create SSH master socket! Diagnostic info: Starting process '/usr/bin/setsid /usr/bin/ssh -M -f -N -o ServerAliveInterval=60 -o ControlPath=/tmp/3Abasy/ssh_socket -p 22 192.168.1.100' Starting process '/usr/bin/setsid /usr/bin/ssh -M -f -N -o ServerAliveInterval=60 -o ControlPath=/tmp/3Abasy/ssh_socket -p 22 192.168.1.100' stdout: =============================== stderr: =============================== No protocol specified (gnome-ssh-askpass:13489): Gtk-WARNING *_: cannot open display: :0 Permission denied, please try again. No protocol specified (gnome-ssh-askpass:13490): Gtk-WARNING *_: cannot open display: :0 Permission denied, please try again. No protocol specified (gnome-ssh-askpass:13491): Gtk-WARNING **: cannot open display: :0 Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password). 

14:50:45 
info  
Establishing connecting to remote target...

14:50:45 
error  
Can't connect to remote machine! Exception was: There was a problem with SshConnection! Failed to create SSH master socket! Diagnostic info: Starting process '/usr/bin/setsid /usr/bin/ssh -M -f -N -o ServerAliveInterval=60 -o ControlPath=/tmp/oS7Dhv/ssh_socket -p 22 192.168.1.100' Starting process '/usr/bin/setsid /usr/bin/ssh -M -f -N -o ServerAliveInterval=60 -o ControlPath=/tmp/oS7Dhv/ssh_socket -p 22 192.168.1.100' stdout: =============================== stderr: =============================== No protocol specified (gnome-ssh-askpass:14830): Gtk-WARNING *_: cannot open display: :0 Permission denied, please try again. No protocol specified (gnome-ssh-askpass:14831): Gtk-WARNING *_: cannot open display: :0 Permission denied, please try again. No protocol specified (gnome-ssh-askpass:14832): Gtk-WARNING **: cannot open display: :0 Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

**Comment by jan-cerny** [comment]
Try to run Workbench under a normal user, not as a root.

**Comment by mpreisler** [comment]
I agree with @jan-cerny here. SCAP Workbench was not designed to be run as root. It looks like it fails to open the ssh-askpass dialog when you run it as root.

**Comment by mpreisler** [comment]
@networkr00 If you run `ssh -vvv root@192.168.1.100` in the terminal what does it say?

**Comment by networkr00** [comment]
[networkr@dfscanner ~]$ ssh -vvv root@192.168.1.100
OpenSSH_5.3p1, OpenSSL 1.0.1e-fips 11 Feb 2013
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Connecting to 192.168.1.100 [192.168.1.100] port 22.
debug1: Connection established.
debug1: identity file /home/networkr/.ssh/identity type -1
debug1: identity file /home/networkr/.ssh/identity-cert type -1
debug1: identity file /home/networkr/.ssh/id_rsa type -1
debug1: identity file /home/networkr/.ssh/id_rsa-cert type -1
debug1: identity file /home/networkr/.ssh/id_dsa type -1
debug1: identity file /home/networkr/.ssh/id_dsa-cert type -1
debug1: identity file /home/networkr/.ssh/id_ecdsa type -1
debug1: identity file /home/networkr/.ssh/id_ecdsa-cert type -1
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1
debug1: match: OpenSSH_6.6.1 pat OpenSSH*
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_5.3
debug2: fd 3 setting O_NONBLOCK
debug1: SSH2_MSG_KEXINIT sent
debug3: Wrote 960 bytes for a total of 981
debug1: SSH2_MSG_KEXINIT received
debug2: kex_parse_kexinit: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-dss-cert-v00@openssh.com,ssh-rsa,ssh-dss
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: first_kex_follows 0 
debug2: kex_parse_kexinit: reserved 0 
debug2: kex_parse_kexinit: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr
debug2: kex_parse_kexinit: hmac-sha1,umac-64@openssh.com,hmac-ripemd160
debug2: kex_parse_kexinit: hmac-sha1,umac-64@openssh.com,hmac-ripemd160
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: first_kex_follows 0 
debug2: kex_parse_kexinit: reserved 0 
debug2: mac_setup: found hmac-sha1
debug1: kex: server->client aes128-ctr hmac-sha1 none
debug2: mac_setup: found hmac-sha1
debug1: kex: client->server aes128-ctr hmac-sha1 none
debug1: SSH2_MSG_KEX_DH_GEX_REQUEST(1024<2048<8192) sent
debug1: expecting SSH2_MSG_KEX_DH_GEX_GROUP
debug3: Wrote 24 bytes for a total of 1005
debug2: dh_gen_key: priv key bits set: 156/320
debug2: bits set: 1009/2048
debug1: SSH2_MSG_KEX_DH_GEX_INIT sent
debug1: expecting SSH2_MSG_KEX_DH_GEX_REPLY
debug3: Wrote 272 bytes for a total of 1277
debug3: check_host_in_hostfile: host 192.168.1.100 filename /home/networkr/.ssh/known_hosts
debug3: check_host_in_hostfile: host 192.168.1.100 filename /home/networkr/.ssh/known_hosts
debug3: check_host_in_hostfile: match line 4
debug1: Host '192.168.1.100' is known and matches the RSA host key.
debug1: Found key in /home/networkr/.ssh/known_hosts:4
debug2: bits set: 1039/2048
debug1: ssh_rsa_verify: signature correct
debug2: kex_derive_keys
debug2: set_newkeys: mode 1
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: Wrote 16 bytes for a total of 1293
debug2: set_newkeys: mode 0
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug3: Wrote 52 bytes for a total of 1345
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug2: key: /home/networkr/.ssh/identity ((nil))
debug2: key: /home/networkr/.ssh/id_rsa ((nil))
debug2: key: /home/networkr/.ssh/id_dsa ((nil))
debug2: key: /home/networkr/.ssh/id_ecdsa ((nil))
debug3: Wrote 68 bytes for a total of 1413
debug3: input_userauth_banner
\S
Kernel \r on an \m

You are accessing a U.S. Government (USG) Information System (IS) that is provided for USG-authorized use only. 

By using this IS (which includes any device attached to this IS), you consent to the following conditions: 

-The USG routinely intercepts and monitors communications on this IS for purposes including, but not limited to, penetration testing, COMSEC monitoring, network operations and defense, personnel misconduct (PM), law enforcement (LE), and counterintelligence (CI) investigations. 

-At any time, the USG may inspect and seize data stored on this IS. 

-Communications using, or data stored on, this IS are not private, are subject to routine monitoring, interception, and search, and may be disclosed or used for any USG-authorized purpose. 

-This IS includes security measures (e.g., authentication and access controls) to protect USG interests -- not for your personal benefit or privacy. 

-Notwithstanding the above, using this IS does not constitute consent to PM, LE or CI investigative searching or monitoring of the content of privileged communications, or work product, related to personal representation or services by attorneys, psychotherapists, or clergy, and their assistants. Such communications and work product are private and confidential. See User Agreement for details.

debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug3: start over, passed a different list publickey,gssapi-keyex,gssapi-with-mic,password
debug3: preferred gssapi-keyex,gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup gssapi-keyex
debug3: remaining preferred: gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_is_enabled gssapi-keyex
debug1: Next authentication method: gssapi-keyex
debug1: No valid Key exchange context
debug2: we did not send a packet, disable method
debug3: authmethod_lookup gssapi-with-mic
debug3: remaining preferred: publickey,keyboard-interactive,password
debug3: authmethod_is_enabled gssapi-with-mic
debug1: Next authentication method: gssapi-with-mic
debug3: Trying to reverse map address 192.168.1.100.
debug1: Unspecified GSS failure.  Minor code may provide more information
Credentials cache file '/tmp/krb5cc_500' not found

debug1: Unspecified GSS failure.  Minor code may provide more information
Credentials cache file '/tmp/krb5cc_500' not found

debug1: Unspecified GSS failure.  Minor code may provide more information


debug1: Unspecified GSS failure.  Minor code may provide more information
Credentials cache file '/tmp/krb5cc_500' not found

debug2: we did not send a packet, disable method
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /home/networkr/.ssh/identity
debug3: no such identity: /home/networkr/.ssh/identity
debug1: Trying private key: /home/networkr/.ssh/id_rsa
debug3: no such identity: /home/networkr/.ssh/id_rsa
debug1: Trying private key: /home/networkr/.ssh/id_dsa
debug3: no such identity: /home/networkr/.ssh/id_dsa
debug1: Trying private key: /home/networkr/.ssh/id_ecdsa
debug3: no such identity: /home/networkr/.ssh/id_ecdsa
debug2: we did not send a packet, disable method
debug3: authmethod_lookup password
debug3: remaining preferred: ,password
debug3: authmethod_is_enabled password
debug1: Next authentication method: password
root@192.168.1.100's password:

**Comment by TheMoves** [comment]
I am also running into a similar issue running - might have to get a newer version: scap-workbench-1.0.2-2.el7.x86_64

**Comment by BobBagwill** [comment]
I had the problem that the remote system wasn't a known host, but the workbench dialog didn't allow responding "yes" to trust it.

**Comment by ktlim86** [comment]
Hi,

I have the same problem running the OpenSCAP workbench on Windows. The workbench never asks me for password. So how do I resolve it? Thanks

**Comment by WesleyCeraso** [comment]
@ktlim86 
Hi, have you tried the last version, [1.1.5-1](https://github.com/OpenSCAP/scap-workbench/releases/download/1.1.5/scap-workbench-1.1.5-1.msi)?

**Comment by WesleyCeraso** [comment]
- scap-workbench should not be run as root
- scap-workbench needs openssh-askpass to ask for user, password and to accept a new key fingerprint, it should have been installed along with scap-workbench, but you can install it anytime.
- on windows, try the last version
