### ISSUE TITLE
1.1.2 CentOS 7 content only opens the datastream for RHEL7 OSP

### ISSUE THREAD

**Issue by sc10n** [OpenSCAP/scap-workbench#76]
In the previous version CentOS7 used the RHEL7 server stream that could be ran. This is not the case anymore.

**Comment by mpreisler** [comment]
Hi, thanks for the bug report! This has actually been an issue in SCAP Security Guide that was fixed in the 0.1.31 release. Shouldn't be an issue anymore in SCAP Workbench.

See https://github.com/OpenSCAP/scap-security-guide/pull/1467
